---
# DESCRIPTION: Github actions config
# This name is key to badges in README.rst, so we use the name build
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: build-test

on:
  push:
    branches-ignore:
      - 'dependabot/**'  # Avoid duplicates: only run the PR, not the push
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly

permissions:
  contents: read
  actions: read

defaults:
  run:
    working-directory: repo

concurrency:
  # At most 1 job per branch. Auto cancel on pull requests and on all forks
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'verilator/verilator' }}

jobs:

  build-2604-gcc:
    name: Build | 26.04 | gcc
    uses: ./.github/workflows/reusable-build.yml
    with:
      cc: gcc
      runs-on: ubuntu-26.04
      sha: ${{ github.sha }}

  lint-py:
    name: Lint Python
    uses: ./.github/workflows/reusable-lint-py.yml
