---
# DESCRIPTION: Github actions config
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

name: reusable-exttest

on:
  workflow_call:
    inputs:
      os:  # e.g. ubuntu-24.04
        required: true
        type: string
      cc:  # gcc or clang
        required: true
        type: string
      suite:  # exttest for compatibility with other reusable's
        required: false
        default: exttest
        type: string

env:
  CI_OS_NAME: linux
  CI_COMMIT: ${{ github.sha }}
  CCACHE_COMPRESS: 1
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_LIMIT_MULTIPLE: 0.95
  INSTALL_DIR: ${{ github.workspace }}/install

defaults:
  run:
    shell: bash
    working-directory: repo

jobs:

  test:
    runs-on: ${{ inputs.os }}
    name: Exttest | ${{ inputs.os }} | ${{ inputs.cc }}
    env:
      CI_BUILD_STAGE_NAME: test
      CI_RUNS_ON: ${{ inputs.os }}
      CC: ${{ inputs.cc }}
      CXX: ${{ inputs.cc == 'clang' && 'clang++' || 'g++' }}
      CACHE_BASE_KEY: test-${{ inputs.os }}-${{ inputs.cc }}-${{ inputs.suite }}
      CCACHE_MAXSIZE: 100M  # Per build per suite (* 5 * 5 = 2500M in total)
      VERILATOR_ARCHIVE: verilator-${{ github.sha }}-${{ inputs.os }}-${{ inputs.cc }}.tar.gz
    steps:

      - name: Checkout verilator_ext_tests
        uses: actions/checkout@v5
        with:
# FIXME need verilator/
          repository: wsnyder/verilator_ext_tests
          ref: 'refs/tags/v1'
          submodules: true
          path: verilator_ext_tests

      - name: Download tar archive
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.VERILATOR_ARCHIVE }}
          path: ${{ github.workspace }}

      - name: Unpack tar archive
        working-directory: ${{ github.workspace }}
        run: tar -x -z -f ${{ env.VERILATOR_ARCHIVE }}

      - name: Cache $CCACHE_DIR
        uses: actions/cache@v4
        env:
          CACHE_KEY: ${{ env.CACHE_BASE_KEY }}-ccache2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CACHE_KEY }}-${{ github.sha }}
          restore-keys: |
            ${{ env.CACHE_KEY }}-

      - name: Install test dependencies
        run: ./ci/ci-install.bash

      - name: Install exttest dependencies
        run: |
          sudo apt-get install libbit-vector-perl || sudo apt-get install libbit-vector-perl
          pipx install ../verilator_ext_tests/submodules/astsee

      - name: Test
        run: |
          export VERILATOR_ROOT=$GITHUB_WORKSPACE/repo
          make -C ../verilator_ext_tests test

      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: wsnyder
